importando bibliotecas

In [84]:
import pandas as pd

carregando os dados (carreguei os datasets para minha maquina)

In [85]:
url_q1_2019 = r"C:\Users\ygorc\OneDrive\Área de Trabalho\StudyCase\Cyclistic\dados_originais\Divvy_Trips_2019_Q1 - Divvy_Trips_2019_Q1.csv"
url_q1_2020 = r"C:\Users\ygorc\OneDrive\Área de Trabalho\StudyCase\Cyclistic\dados_originais\Divvy_Trips_2020_Q1 - Divvy_Trips_2020_Q1.csv"

df_2019 = pd.read_csv(url_q1_2019)
df_2020 = pd.read_csv(url_q1_2020)

Verificando a compatibilidade

In [86]:
print(list(df_2019.columns))
print(list(df_2020.columns))

['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration', 'from_station_id', 'from_station_name', 'to_station_id', 'to_station_name', 'usertype', 'gender', 'birthyear']
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual']

Observa-se que a arquitetura do banco de dados da cyclistic foi aletrada

In [87]:
print(df_2019.info())
print(df_2020.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365069 entries, 0 to 365068
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            365069 non-null  int64
 1   start_time         365069 non-null  object
 2   end_time           365069 non-null  object
 3   bikeid             365069 non-null  int64
 4   tripduration       365069 non-null  object
 5   from_station_id    365069 non-null  int64
 6   from_station_name  365069 non-null  object
 7   to_station_id      365069 non-null  int64
 8   to_station_name    365069 non-null  object
 9   usertype           365069 non-null  object
 10  gender             345358 non-null  object
 11  birthyear          347046 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 33.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426887 entries, 0 to 426886
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             426887 non-null  object
 1   rideable_type       426887 non-null  object
 2   started_at          426887 non-null  object
 3   ended_at            426887 non-null  object
 4   start_station_name  426887 non-null  object
 5   start_station_id    426887 non-null  int64
 6   end_station_name    426886 non-null  object
 7   end_station_id      426886 non-null  float64
 8   start_lat           426887 non-null  float64
 9   start_lng           426887 non-null  float64
 10  end_lat             426886 non-null  float64
 11  end_lng             426886 non-null  float64
 12  member_casual       426887 non-null  object
dtypes: float64(5), int64(1), object(7)
memory usage: 42.3+ MB
None

Os tipos de dados mudaram, em destaque o ID* passou a ser :object

In [88]:
display(df_2019.head())
display(df_2020.head())

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,21742443,2019-01-01 0:04:37,2019-01-01 0:11:07,2167,390,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0
1,21742444,2019-01-01 0:08:13,2019-01-01 0:15:34,4386,441,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0
2,21742445,2019-01-01 0:13:23,2019-01-01 0:27:12,1524,829,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0
3,21742446,2019-01-01 0:13:45,2019-01-01 0:43:28,252,"1,783.00",123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0
4,21742447,2019-01-01 0:14:52,2019-01-01 0:20:56,1170,364,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,EACB19130B0CDA4A,docked_bike,2020-01-21 20:06:59,2020-01-21 20:14:30,Western Ave & Leland Ave,239,Clark St & Leland Ave,326.0,41.9665,-87.6884,41.9671,-87.6674,member
1,8FED874C809DC021,docked_bike,2020-01-30 14:22:39,2020-01-30 14:26:22,Clark St & Montrose Ave,234,Southport Ave & Irving Park Rd,318.0,41.9616,-87.6660,41.9542,-87.6644,member
2,789F3C21E472CA96,docked_bike,2020-01-09 19:29:26,2020-01-09 19:32:17,Broadway & Belmont Ave,296,Wilton Ave & Belmont Ave,117.0,41.9401,-87.6455,41.9402,-87.6530,member
3,C9A388DAC6ABF313,docked_bike,2020-01-06 16:17:07,2020-01-06 16:25:56,Clark St & Randolph St,51,Fairbanks Ct & Grand Ave,24.0,41.8846,-87.6319,41.8918,-87.6206,member
4,943BC3CBECCFD662,docked_bike,2020-01-30 8:37:16,2020-01-30 8:42:48,Clinton St & Lake St,66,Wells St & Hubbard St,212.0,41.8856,-87.6418,41.8899,-87.6343,member

Removendo colunas incompativeis

In [89]:
df_2019 = df_2019.drop(columns=['gender', 'birthyear', 'bikeid', 'tripduration'])
df_2020 = df_2020.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng', 'rideable_type'])

Renomeando as colunas equivalentes

In [90]:
df_2019 = df_2019.rename(columns={
    'trip_id': 'ride_id',
    'start_time': 'started_at',
    'end_time': 'ended_at',
    'from_station_id': 'start_station_id',
    'from_station_name': 'start_station_name',
    'to_station_id': 'end_station_id',
    'to_station_name': 'end_station_name',
    'usertype': 'member_casual'
})

Transformando os tipos dos dados os tornando compativeis

In [91]:
df_2019['ride_id'] = df_2019['ride_id'].astype(str)
df_2020['start_station_id'] = df_2020['start_station_id'].astype(str)
df_2020['end_station_id'] = df_2020['end_station_id'].astype(str)

Criando o DataFrame com os 2 blocos de dados

In [92]:
df_completo = pd.concat([df_2019, df_2020], ignore_index=True)

In [93]:
df_completo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791956 entries, 0 to 791955
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             791956 non-null  object
 1   started_at          791956 non-null  object
 2   ended_at            791956 non-null  object
 3   start_station_id    791956 non-null  object
 4   start_station_name  791956 non-null  object
 5   end_station_id      791956 non-null  object
 6   end_station_name    791955 non-null  object
 7   member_casual       791956 non-null  object
dtypes: object(8)
memory usage: 48.3+ MB

Transformando as colunas de inicio de viagem e fim de viagem em colunas de tipo: datetime

In [94]:
df_completo['started_at'] = pd.to_datetime(df_completo['started_at'])
df_completo['ended_at'] = pd.to_datetime(df_completo['ended_at'])

Criando a coluna tripduration que é igual ao tempo de cada viagem

In [95]:
df_completo['ride_length'] = (df_completo['ended_at'] - df_completo['started_at']).dt.total_seconds()

Notei que o nome que representava o tipo de usuariopassou por mudanças base de dados da cyclistic e por isso apresentava uma divergencia entre os dados da coluna: "member_casual" de 2019 e 2019

In [96]:
df_completo['member_casual'] = df_completo['member_casual'].replace({
    'Subscriber' : 'member',
    'Customer' : 'casual'
})

Como podemos ver abaixo, existiam anomalias nos dados de trip duration onde existiam viagens com tempo de viagem negativo, o que é fisicamente impossivel, por isso optei por tirar as viagens que possuiram menos de 0 segundos

In [97]:
df_completo['ride_length'].describe()

count    7.919560e+05
mean     1.183813e+03
std      3.321274e+04
min     -5.520000e+02
25%      3.280000e+02
50%      5.370000e+02
75%      9.100000e+02
max      1.063202e+07
Name: ride_length, dtype: float64

In [98]:
df_completo = df_completo[df_completo['ride_length'] > 0]

In [99]:
df_completo['day_of_week'] = df_completo['started_at'].dt.day_name()

Total de viagens por tipo de usuario:

In [100]:
df_completo['member_casual'].value_counts()

member_casual
member    720313
casual     71433
Name: count, dtype: int64

tempo de viagem vs tipo de usuario:

In [101]:
df_completo.groupby('member_casual')['ride_length'].mean()

member_casual
casual    5105.487856
member     795.251260
Name: ride_length, dtype: float64

volume vs tipo de usuario vs dia da semana:

obs: aqui optei por criar um script ordenando os dias da semana, para ficar mais facil de indentificar tendencias

In [104]:
ordem_dias = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df_completo['day_of_week'] = pd.Categorical(df_completo['day_of_week'], categories=ordem_dias, ordered=True)

viagens_por_dia = df_completo.groupby(['member_casual', 'day_of_week'])['ride_id'].count().reset_index()
display(viagens_por_dia.sort_values(['member_casual', 'day_of_week']))

C:\Users\ygorc\AppData\Local\Temp\ipykernel_4136\2804637444.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  viagens_por_dia = df_completo.groupby(['member_casual', 'day_of_week'])['ride_id'].count().reset_index()

   member_casual day_of_week  ride_id
0         casual      Monday     6694
1         casual     Tuesday     7972
2         casual   Wednesday     8363
3         casual    Thursday     7771
4         casual      Friday     8508
5         casual    Saturday    13473
6         casual      Sunday    18652
7         member      Monday   110430
8         member     Tuesday   127974
9         member   Wednesday   121903
10        member    Thursday   125228
11        member      Friday   115168
12        member    Saturday    59413
13        member      Sunday    60197

In [ ]:
df_completo.to_csv('cyclistic_dados_limpos.csv', index=False)

Aqui eu salvo o df_completo com os dados limpos e uma analise previa bem eficiente para me possibilitar uma descrição detalhada por meio da visualização destes dados no tableau ou power bi